### ISSUE TITLE
OAuth2 Error; Missing "redirect_uri" in request

### ISSUE THREAD

**Issue by laserzz** [TheUntraceable/Discord2Terminal#1]
### Summary
I have setup the config.json file correctly, and set up a bot application and provided the credentials, however, an error is still thrown when I click authorize.

### Error
**Error: OAuth2 Error: invalid_request: Missing "redirect_uri" in request.**

### Other Info

I've tried both with and without the port, and I haven't altered the files themselves.

**Comment by TheUntraceable** [comment]
I can't find the solution, nor can I replicate this assuming that you've done everything correctly.
